services:
  db:
    container_name: quest-postgres-db
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "2345:5432"
    volumes:
      - postgresql_quest_data:/var/lib/postgresql/data

  app:
    container_name: quests-app
    image: quests
    build: .
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_THYMELEAF_PREFIX: ${SPRING_THYMELEAF_PREFIX}
      APP_IMAGES_DIRECTORY: ${APP_IMAGES_DIRECTORY}
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgresql_quest_data: