services:
  db:
    container_name: quest-postgres-db
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql_quest_data:/var/lib/postgresql/data
    networks:
      - quests-network

  app:
    container_name: quests-app
    image: quests
    build: .
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_THYMELEAF_PREFIX: ${SPRING_THYMELEAF_PREFIX}
      APP_IMAGES_DIRECTORY: ${APP_IMAGES_DIRECTORY}
    networks:
      - quests-network
    depends_on:
      - db

networks:
  quests-network:

volumes:
  postgresql_quest_data: