services:
  db:
    container_name: ${DATABASE_CONTAINER_NAME}
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql_quest_data:/var/lib/postgresql/data
    networks:
      - quests-network

  app:
    container_name: ${FINAL_APP_CONTAINER_NAME}
    image: ${FINAL_IMAGE_NAME}
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      APP_DIRECTORIES_IMAGES: ${APP_DIRECTORIES_IMAGES}
    networks:
      - quests-network
    depends_on:
      - db
    privileged: true
    volumes:
      - ${HOST_LOGS_DIR}:/app/logs
      - ${HOST_IMAGES_DIR}:/app/images
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  quests-network:

volumes:
  postgresql_quest_data: