spring:
  datasource:
    url: jdbc:postgresql://localhost:2345/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 10
      minimumIdle: 5
      idleTimeout: 300000
      maxLifetime: 600000
      autoCommit: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
    open-in-view: true
  messages:
    encoding: UTF-8
    basename: messages
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    default-schema: public
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      springframework:
        web: DEBUG
        orm:
          jpa:
            JpaTransactionManager: DEBUG

app:
  default-locale: en
  images-directory: src/main/webapp/WEB-INF/images/

images:
  resource:
    handler: /images/**
    locations: classpath:/images/
    temp:
      handler: /images/temp/**
      locations: classpath:/images/temp/
ico:
  resource:
    handler: /images/icon/**
    locations: classpath:/static/images/icon/